"""Init

Revision ID: 1186c267cbe1
Revises: 
Create Date: 2023-11-22 01:12:25.869438

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '1186c267cbe1'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('comments', sa.Column('photo_id', sa.Integer(), nullable=True))
    op.alter_column('comments', 'text',
               existing_type=sa.TEXT(),
               nullable=True)
    op.alter_column('comments', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.alter_column('comments', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.alter_column('comments', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('comments', 'update_status',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.drop_constraint('comments_image_id_fkey', 'comments', type_='foreignkey')
    op.create_foreign_key(None, 'comments', 'images', ['photo_id'], ['id'], ondelete='CASCADE')
    op.drop_column('comments', 'image_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('comments', sa.Column('image_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'comments', type_='foreignkey')
    op.create_foreign_key('comments_image_id_fkey', 'comments', 'images', ['image_id'], ['id'], ondelete='CASCADE')
    op.alter_column('comments', 'update_status',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.alter_column('comments', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('comments', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.alter_column('comments', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.alter_column('comments', 'text',
               existing_type=sa.TEXT(),
               nullable=False)
    op.drop_column('comments', 'photo_id')
    # ### end Alembic commands ###
